### ISSUE TITLE
>info broken

### ISSUE THREAD

**Issue by Blattoid** [Blattoid/Python-Discord-Bot#3]
Full error message:
```2019/8/15 0:15:52: Traceback (most recent call last):
  File "bot.py", line 266, in on_message
    await action(passedvariables)
  File "C:\Users\Daniel\Source\DiscordBots\Wheatley\Source-Code\commands.py", line 271, in info
    embed = discord.Embed(title="Data dump for user "+user.name+"#"+user.discriminator)
UnboundLocalError: local variable 'user' referenced before assignment

**Comment by Blattoid** [comment]
Solution was to use the fetch_user function instead of the now deprecated get_user_info, which only returns NoneTypes and thus variable 'user' would never be initialised.
