### ISSUE TITLE
Endless crashes

### ISSUE THREAD

**Issue by Blattoid** [Blattoid/Python-Discord-Bot#7]
11/20 18:18:58 [bot] Fatal exception caused bot crash.
11/20 18:18:58 [bot] Waiting 10 second before restarting...
11/20 18:19:08 [bot] Fatal exception caused bot crash.
11/20 18:19:08 [bot] Waiting 10 second before restarting...
11/20 18:19:18 [bot] Fatal exception caused bot crash.
11/20 18:19:18 [bot] Waiting 10 second before restarting...
11/20 18:19:28 [bot] Fatal exception caused bot crash.
11/20 18:19:28 [bot] Waiting 10 second before restarting...
11/20 18:19:38 [bot] Fatal exception caused bot crash.
11/20 18:19:38 [bot] Waiting 10 second before restarting...
11/20 18:19:48 [bot] Fatal exception caused bot crash.
11/20 18:19:48 [bot] Waiting 10 second before restarting...

**Comment by Blattoid** [comment]
Got a traceback, why the hell is the event loop closed?? Maybe that can be answered by looking at the very first instance of an error.

11/20 18:53:47 [bot] Waiting 10 second before restarting...
11/20 18:53:57 [bot] Fatal exception caused bot crash.
Traceback (most recent call last):
  File "/home/daniel/DiscordBots/Python-Discord-Bot/bot.py", line 90, in <module>
    try: bot.run(token)
  File "/home/daniel/.local/lib/python3.7/site-packages/discord/client.py", line 680, in run
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 86, in add_signal_handler
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Blattoid** [comment]
First error is like this
```
... very long traceback...
raise last_exc
  File "/home/daniel/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 1034, in _create_direct_connection
    client_error=client_error,
  File "/home/daniel/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 977, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Network is unreachable]

PRESS ENTER TO RETRY.
11/20 19:19:42 [bot] Fatal exception caused bot crash.
Traceback (most recent call last):
  File "/home/daniel/DiscordBots/Python-Discord-Bot/bot.py", line 90, in <module>
    try: bot.run(token)
  File "/home/daniel/.local/lib/python3.7/site-packages/discord/client.py", line 680, in run
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 86, in add_signal_handler
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
...repeat forever ...
```
